openapi: 3.0.0
info:
  title: Интеграция СКУД API Ovision
  description:
    Данное API предназначено для подключения СКУД систем к терминалу устройств
    O.Gate через открытый протокол openapi-3.0.0
  version: 1.0.0
servers:
  - url: http://localhost/
tags:
  - name: Управление интеграцией
    description: Методы для работы с интеграцией
paths:
  /syncSettings:
    post:
      security:
        - bearerAuth: []
      tags:
        - Управление интеграцией
      summary: Синхронизация настроек
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/APIConfig"
        required: false
      responses:
        200:
          description: Group list response!
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/AnswerRequest"
                  status:
                    type: string
                    example: success
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /syncEvent:
    post:
      security:
        - bearerAuth: []
      tags:
        - Управление интеграцией
      summary: Синхронизация событий
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/SyncEvent"
        required: false
      responses:
        200:
          description: Group list response!
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/AnswerRequest"
                  status:
                    type: string
                    example: success
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
  schemas:
    APIConfig:
      type: object
      properties:
        iid:
          type: integer
          example: 1
        target:
          type: string
          example: "titleIntegration"
        terminal_url:
          type: string
          example: "http://127.0.0.1:8080"
        sync_key:
          type: string
        action:
          type: string
          enum:
            - "set"
            - "init"
          example: "set"
        settings:
          type: string
          description: "Структора полей для веб интерфейса (не обязательное поле)"
        enable:
          type: boolean

    SyncEvent:
      type: object
      properties:
        id:
          type: integer
        integration:
          type: integer
        event:
          type: string
        metadata:
          type: string
        synckey:
          type: string
        created_at:
          type: string

    AnswerRequest:
      type: object
      properties:
        status:
          type: string
          enum:
            - "success"
            - "error"
          example: "success"
        success:
          type: boolean
        message:
          type: string
        result:
          type: string

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
